apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-sample
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-sample
  template:
    metadata:
      labels:
        app: quarkus-sample
    spec:
      containers:
        - name: quarkus
          image: quay.io/your-username/quarkus-sample-quarkus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:mysql://mysql-service:3306/quarkus_db
            - name: QUARKUS_DATASOURCE_USERNAME
              value: mysql
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name: jwt-secret
              mountPath: /secrets
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: jwt-secret
          secret:
            secretName: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
  namespace: default
spec:
  selector:
    app: quarkus-sample
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP